### ISSUE TITLE
ModuleNotFoundError: No module named 'main' when accesing http://localhost:5000/

### ISSUE THREAD

**Issue by sebastianhritcu** [parthk3004/Quizzaro#2]
Hello,

When running your project the below error appears when you execute the same project?

ModuleNotFoundError
ModuleNotFoundError: No module named 'main'
Traceback (most recent call last)
File "s:\quizzaro\env\lib\site-packages\flask_cli\cli.py", line 174, in __call__
self._flush_bg_loading_exception()
File "s:\quizzaro\env\lib\site-packages\flask_cli\cli.py", line 162, in _flush_bg_loading_exception
reraise(*exc_info)
File "s:\quizzaro\env\lib\site-packages\flask_cli\_compat.py", line 25, in reraise
raise value
File "s:\quizzaro\env\lib\site-packages\flask_cli\cli.py", line 151, in _load_app
self._load_unlocked()
File "s:\quizzaro\env\lib\site-packages\flask_cli\cli.py", line 166, in _load_unlocked
self._app = rv = self.loader()
File "s:\quizzaro\env\lib\site-packages\flask_cli\cli.py", line 226, in load_app
rv = locate_app(self.app_import_path)
File "s:\quizzaro\env\lib\site-packages\flask_cli\cli.py", line 90, in locate_app
__import__(module)
ModuleNotFoundError: No module named 'main'

**Comment by parthk3004** [comment]
Ok, so there was problem in main.py file. now you can clone repository and you can use main.py file from main folder and it will work.
